### ISSUE TITLE
Support CURRENT_DATE()

### ISSUE THREAD

**Issue by marcj** [synatic/sql-to-mongo#82]
Please add support for `CURRENT_DATE()`.

I currently get `Error: Function:CURRENT_DATE not available`.

My query:

```sql
SELECT COUNT(*) as count, MONTH(data.returnDate) as month 
FROM package 
WHERE YEAR(data.returnDate) = YEAR(CURRENT_DATE()) 
GROUP BY MONTH(data.returnDate)
```

**Comment by eXigentCoder** [comment]
Hi there, apologies as we have been away over the December holidays, I will take a look asap and get back to you!

**Comment by marcj** [comment]
Awesome, thank you!
